name: Build and Release Flutter Apps

on:
  push:
    branches:
      - main

jobs:
  build-windows:
    name: Build Windows App
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create .env file from secrets
        run: |
          cat << 'EOF' > .env
          ${{ secrets.ENV_FILE }}
          EOF

      - name: Get dependencies
        run: flutter pub get

      - name: Build Windows App
        run: flutter build windows --release

      - name: Compile Inno Setup Installer
        run: iscc windows_installer.iss

      - name: Upload Windows Installer
        uses: actions/upload-artifact@v4
        with:
          name: ArgityTurnos-Windows-Installer
          path: Output/*.exe

  build-macos:
    name: Build macOS App
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create .env file from secrets
        run: |
          cat << 'EOF' > .env
          ${{ secrets.ENV_FILE }}
          EOF

      - name: Get dependencies
        run: flutter pub get

      - name: Build macOS App
        run: flutter build macos --release

      - name: Compress macOS App
        run: |
          cd build/macos/Build/Products/Release
          zip -r ../../../../../ArgityTurnos-macOS.zip *.app

      - name: Upload macOS App
        uses: actions/upload-artifact@v4
        with:
          name: ArgityTurnos-macOS-App
          path: ArgityTurnos-macOS.zip
